function toM(t){var p=t.split(':');return+p[0]*60+(+p[1])}
var TH=['#000000','#44546A','#4472C4','#ED7D31','#A5A5A5','#FFC000','#5B9BD5','#70AD47','#D6DCE4','#D9E2F3','#FCE4D6','#EDEDED','#FFF2CC','#DEEBF6','#E2EFDA','#ADB9CA','#B4C6E7','#F8CBAD','#DBDBDB','#FFE699','#BDD7EE','#C5E0B3','#8496B0','#8EAADB','#F4B183','#C9C9C9','#FFD966','#9CC3E5','#A8D08D','#5B758E','#5B9BD5','#C55A11','#FFC000','#2E75B6','#548235'];
var SD=['#C00000','#FF0000','#FFC000','#FFFF00','#92D050','#00B050','#00B0F0','#0070C0','#002060','#7030A0'];
function mkP(rid,iid,ref){var r=document.getElementById(rid),all=TH.concat(SD);all.forEach(function(c){var d=document.createElement('div');d.className='cs2';d.style.background=c;d.setAttribute('data-c',c);d.onclick=function(){ref.v=c;document.getElementById(iid).value=c;r.querySelectorAll('.cs2').forEach(function(x){x.classList.toggle('on',x.getAttribute('data-c')===c)});pvL()};r.appendChild(d)});document.getElementById(iid).oninput=function(){ref.v=this.value;r.querySelectorAll('.cs2').forEach(function(x){x.classList.remove('on')});pvL()}}
function pvL(){if(!window._cfg)return;document.getElementById('mc').style.color=window._tc;document.documentElement.style.setProperty('--earn',window._ec);var co=+(document.getElementById('fCO').value)||85,bo=+(document.getElementById('fBO').value)||6;document.documentElement.style.setProperty('--cop',co/100);document.documentElement.style.setProperty('--bop',bo/100);document.getElementById('fCOv').textContent=co+'%';document.getElementById('fBOv').textContent=bo+'%'}
function apL(c){window._tc=c.text_color||'#eae6de';window._ec=c.earn_color||'#e8b84b';document.getElementById('mc').style.color=window._tc;document.documentElement.style.setProperty('--earn',window._ec);var co=c.card_op!=null?c.card_op:85,bo=c.bord_op!=null?c.bord_op:6;document.documentElement.style.setProperty('--cop',co/100);document.documentElement.style.setProperty('--bop',bo/100);document.getElementById('tcI').value=window._tc;document.getElementById('ecI').value=window._ec;document.getElementById('fCO').value=co;document.getElementById('fBO').value=bo;document.getElementById('fCOv').textContent=co+'%';document.getElementById('fBOv').textContent=bo+'%';document.querySelectorAll('#tcR .cs2').forEach(function(x){x.classList.toggle('on',x.getAttribute('data-c')===window._tc)});document.querySelectorAll('#ecR .cs2').forEach(function(x){x.classList.toggle('on',x.getAttribute('data-c')===window._ec)})}
function lBg(){var b=localStorage.getItem('dayW3bg'),mc=document.getElementById('mc');if(b){document.getElementById('bpI').src=b;document.getElementById('bpI').style.display='block';document.getElementById('bpP').style.display='none';mc.style.backgroundImage='url('+b+')';mc.classList.add('hb')}else{document.getElementById('bpI').style.display='none';document.getElementById('bpP').style.display='flex';mc.style.backgroundImage='none';mc.classList.remove('hb')}}
function aZ(){document.documentElement.style.setProperty('sc',window._zl/100);document.getElementById('zV').textContent=window._zl+'%';localStorage.setItem('dayW3z',window._zl)}
function lCfg(){try{var r=localStorage.getItem('dayW3');if(r){var d=JSON.parse(r),c={};for(var k in window._DF)c[k]=d[k]!=null?d[k]:window._DF[k];return c}}catch(e){}return null}
function sS(c){localStorage.setItem('dayW3',JSON.stringify(c))}
function gM(d){var dt=new Date(d.getFullYear(),d.getMonth(),d.getDate()),w=dt.getDay();if(!w)dt.setDate(dt.getDate()-6);else dt.setDate(dt.getDate()-w+1);return dt}
function gW(a,b){return Math.round((gM(a)-gM(b))/6048e5)}
function iB(dt,r,i){return gW(dt,r)%2===0?i:!i}
function iWD(y,m,d,c){var w=new Date(y,m,d).getDay();if(c.rest_mode==='double')return w>0&&w<6;if(c.rest_mode==='single')return c.single_rest_day==='saturday'?w!==5:w!==0;if(c.rest_mode==='alternate')return iB(new Date(y,m,d),new Date(c.ref_monday_ts),c.ref_is_big)?w!==0:w>0&&w<6;return true}
function cWD(y,m,c){var n=new Date(y,m+1,0).getDate(),t=0;for(var d=1;d<=n;d++)if(iWD(y,m,d,c))t++;return t}
function gDH(c){return Math.max(0,(toM(c.work_end)-toM(c.work_start)-toM(c.lunch_end)+toM(c.lunch_start))/60)}
function gDHT(c){var w=Math.max(0,(toM(c.work_end)-toM(c.work_start))-(toM(c.lunch_end)-toM(c.lunch_start)));return Math.floor(w/60)+'时'+(w%60?w%60+'分':'')}
function gDS(c){var dh=gDH(c);if(dh<=0)return 0;if(c.calc_mode==='legal')return c.salary/21.75;var n=new Date;if(!iWD(n.getFullYear(),n.getMonth(),n.getDate(),c))return 0;var wd=cWD(n.getFullYear(),n.getMonth(),c);return wd?c.salary/wd:0}
function gHR(c){var dh=gDH(c);if(dh<=0)return 0;if(c.calc_mode==='legal')return c.salary/174;var n=new Date;if(!iWD(n.getFullYear(),n.getMonth(),n.getDate(),c))return 0;var wd=cWD(n.getFullYear(),n.getMonth(),c);return wd?c.salary/(wd*dh):0}
function gEH(c){var n=new Date,s=n.getHours()*3600+n.getMinutes()*60+n.getSeconds(),ws=toM(c.work_start)*60,we=toM(c.work_end)*60,ls=toM(c.lunch_start)*60,le=toM(c.lunch_end)*60;if(s<=ws)return 0;if(s>=we)return(we-ws-(le-ls))/3600;var e=s-ws;if(s>le)e-=le-ls;else if(s>ls)e-=s-ls;return Math.max(0,e/3600)}
function gTE(c){var n=new Date;if(!iWD(n.getFullYear(),n.getMonth(),n.getDate(),c))return c.calc_mode==='legal'?c.salary/21.75:0;var s=gSt(c);return s==='off'?gDS(c):gEH(c)*gHR(c)}
function gSt(c){var n=new Date;if(!iWD(n.getFullYear(),n.getMonth(),n.getDate(),c))return'rest';var s=n.getHours()*3600+n.getMinutes()*60+n.getSeconds(),ws=toM(c.work_start)*60,we=toM(c.work_end)*60,ls=toM(c.lunch_start)*60,le=toM(c.lunch_end)*60;if(s<ws)return'waiting';if(s>=we)return'off';if(s>=ls&&s<le)return'lunch';return'working'}
function render(){if(!window._cfg)return;var n=new Date,y=n.getFullYear(),m=n.getMonth(),d=n.getDate(),hh=n.getHours(),mi=n.getMinutes(),ss=n.getSeconds(),e=document.getElementById;e('cH').textContent=(hh<10?'0':'')+hh;e('cM').textContent=(mi<10?'0':'')+mi;e('cS').textContent=(ss<10?'0':'')+ss;e('dL').textContent=y+'年'+(m<9?'0':'')+(0':'')+d+'日 '+window._WK[n.getDay()];var st=gSt(window._cfg),clr=st==='working'?'rgba(45,214,122,.1)':st==='waiting'?'rgba(91,141,239,.1)':st==='lunch'?'rgba(232,184,75,.m+1)+'月'+(d<10?'1)':st==='rest'?'rgba(140,100,200,.1)':'rgba(255,255,255,.04)',fc=st==='working'?'#2dd67a':st==='waiting'?'#5b8def':st==='lunch'?'#e8b84b':st==='rest'?'#a080d0':'#8a869a',tx=st==='working'?'工作中':st==='waiting'?'等待上班':st==='lunch'?'午休中':st==='rest'?'今日休息':'已下班';e('bdg').style.background=clr;e('bdg').style.color=fc;e('stx').textContent='● '+tx;if(window._cfg.rest_mode==='alternate'){var big=iB(n,new Date(window._cfg.ref_monday_ts),window._cfg.ref_is_big);e('wkT').style.display='';e('wkT').textContent=big?'大周':'小周';e('wkT').style.background=big?'rgba(232,184,75,.1)':'rgba(91,141,239,.1)';e('wkT').style.color=big?'#e8b84b':'#5b8def'}else e('wkT').style.display='none';var ds=gDS(window._cfg),hr=gHR(window._cfg),te=gTE(window._cfg),iw=iWD(y,m,d,window._cfg);e('tE').textContent=te.toFixed(2);var wd=cWD(y,m,window._cfg),dh=gDH(window._cfg),dy=ds,pa=0;for(var dd=1;dd<d;dd++)if(iWD(y,m,dd,window._cfg))pa++;e('mE').textContent=(pa*dy+te).toFixed(2);var pc=dh>0?Math.min(100,gEH(window._cfg)/dh*100):0;if(!iw)pc=st==='off'?100:0;e('pp').textContent=Math.round(pc)+'%';e('pfl').style.width=pc+'%';e('iH').textContent=gDHT(window._cfg);if(iw||window._cfg.calc_mode==='legal'){e('iDS').textContent='¥'+ds.toFixed(1);e('iR').textContent='¥'+hr.toFixed(1)}else{e('iDS').textContent='¥0';e('iR').textContent='¥0'}var ns=hh*3600+mi*60+ss;if(st==='off'||st==='rest'){e('iT').textContent=st==='off'?'已下班':'--'}else{var tg=st==='waiting'?toM(window._cfg.work_start)*60:toM(window._cfg.work_end)*60,df=Math.max(0,tg-ns);e('iT').textContent=(df<10?'0':'')+Math.floor(df/3600)+':'+((df%3600)/60<10?'0':'')+Math.floor((df%3600)/60)}var pd=window._cfg.pay_day,md=new Date(y,m+1,0).getDate();if(d===pd)e('iP').textContent='今天';else if(d<pd)e('iP').textContent=(pd-d)+'天';else e('iP').textContent=(md-d+pd)+'天';var re=e('rm');if(st==='off'){re.style.display='block';re.innerHTML='<div>上班辛苦了，今日赚取</div><div class="ra">¥'+te.toFixed(2)+'</div>'}else if(st==='rest'){re.style.display='block';re.innerHTML=window._cfg.calc_mode==='legal'?'<div>放假快乐！今日赚取</div><div class="ra">¥'+te.toFixed(2)+'</div>':'<div>放假快乐！</div>'}else re.style.display='none';e('fi').textContent='本月'+wd+'个工作日·已过'+pa+'天·剩余'+Math.max(0,wd-pa-(iw?1:0))+'天'}
function openS(){var c=window._cfg,e=document.getElementById;if(c){e('fS').value=c.salary;e('fWS').value=c.work_start;e('fWE').value=c.work_end;e('fLS').value=c.lunch_start;e('fLE').value=c.lunch_end;e('fPD').value=c.pay_day;sRM(c.rest_mode);sRD(c.single_rest_day);sAW(c.ref_is_big?'big':'small');sCM(c.calc_mode||'actual');window._tc=c.text_color||'#eae6de';window._ec=c.earn_color||'#e8b84b';apL(c)}e('ov').classList.add('on');e('sh').classList.add('on')}
function closeS(){document.getElementById('ov').classList.remove('on');document.getElementById('sh').classList.remove('on')}
function sRM(v){document.querySelectorAll('#rmG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'});document.getElementById('sRW').className=v==='single'?'sr2 show':'sr2';document.getElementById('aRW').className=v==='alternate'?'sr2 show':'sr2'}
function sRD(v){document.querySelectorAll('#rdG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'})}
function sAW(v){document.querySelectorAll('#awG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'})}
function sCM(v){document.querySelectorAll('#cmG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'});document.getElementById('cmD').innerHTML=v==='legal'?'时薪=月薪÷174小时':'时薪=月薪÷当月工作日÷日工时'}
function toast(m){var t=document.getElementById('toast');t.textContent=m;t.classList.add('show');setTimeout(function(){t.classList.remove('show')},1600)}
