(function(){
var WK=['星期日','星期一','星期二','星期三','星期四','星期五','星期六'];
var DF={salary:8000,work_start:'09:00',work_end:'18:00',lunch_start:'12:00',lunch_end:'13:00',rest_mode:'double',single_rest_day:'sunday',ref_monday_ts:0,ref_is_big:true,pay_day:10,calc_mode:'actual',text_color:'#eae6de',earn_color:'#e8b84b',card_op:85,bord_op:6};
var cfg=null,zl=100,tc='#eae6de',ec='#e8b84b';
function $(id){return document.getElementById(id)}
function toM(t){var p=t.split(':');return+p[0]*60+(+p[1])}
var TH=['#000000','#44546A','#4472C4','#ED7D31','#A5A5A5','#FFC000','#5B9BD5','#70AD47','#D6DCE4','#D9E2F3','#FCE4D6','#EDEDED','#FFF2CC','#DEEBF6','#E2EFDA','#ADB9CA','#B4C6E7','#F8CBAD','#DBDBDB','#FFE699','#BDD7EE','#C5E0B3','#8496B0','#8EAADB','#F4B183','#C9C9C9','#FFD966','#9CC3E5','#A8D08D','#5B758E','#5B9BD5','#C55A11','#FFC000','#2E75B6','#548235'];
var SD=['#C00000','#FF0000','#FFC000','#FFFF00','#92D050','#00B050','#00B0F0','#0070C0','#002060','#7030A0'];
function mkP(rid,iid,ref){var r=$(rid),all=TH.concat(SD);all.forEach(function(c){var d=document.createElement('div');d.className='cs2';d.style.background=c;d.setAttribute('data-c',c);d.onclick=function(){ref.v=c;$(iid).value=c;r.querySelectorAll('.cs2').forEach(function(x){x.classList.toggle('on',x.getAttribute('data-c')===c)});pvL()};r.appendChild(d)});$(iid).oninput=function(){ref.v=this.value;r.querySelectorAll('.cs2').forEach(function(x){x.classList.remove('on')});pvL()}}
function pvL(){if(!cfg)return;$('mc').style.color=tc;document.documentElement.style.setProperty('--earn',ec);var co=+$('fCO').value||85,bo=+$('fBO').value||6;document.documentElement.style.setProperty('--cop',co/100);document.documentElement.style.setProperty('--bop',bo/100);$('fCOv').textContent=co+'%';$('fBOv').textContent=bo+'%'}
function apL(c){tc=c.text_color||'#eae6de';ec=c.earn_color||'#e8b84b';$('mc').style.color=tc;document.documentElement.style.setProperty('--earn',ec);var co=c.card_op!=null?c.card_op:85,bo=c.bord_op!=null?c.bord_op:6;document.documentElement.style.setProperty('--cop',co/100);document.documentElement.style.setProperty('--bop',bo/100);$('tcI').value=tc;$('ecI').value=ec;$('fCO').value=co;$('fBO').value=bo;$('fCOv').textContent=co+'%';$('fBOv').textContent=bo+'%';document.querySelectorAll('#tcR .cs2').forEach(function(x){x.classList.toggle('on',x.getAttribute('data-c')===tc)});document.querySelectorAll('#ecR .cs2').forEach(function(x){x.classList.toggle('on',x.getAttribute('data-c')===ec)})}
function lBg(){var b=localStorage.getItem('dayW3bg');if(b){$('bpI').src=b;$('bpI').style.display='block';$('bpP').style.display='none';$('mc').style.backgroundImage='url('+b+')';$('mc').classList.add('hb')}else{$('bpI').style.display='none';$('bpP').style.display='flex';$('mc').style.backgroundImage='none';$('mc').classList.remove('hb')}}
function aZ(){document.documentElement.style.setProperty('sc',zl/100);$('zV').textContent=zl+'%';localStorage.setItem('dayW3z',zl)}
function lCfg(){try{var r=localStorage.getItem('dayW3');if(r){var d=JSON.parse(r),c={};for(var k in DF)c[k]=d[k]!=null?d[k]:DF[k];return c}}catch(e){}return null}
function sS(c){localStorage.setItem('dayW3',JSON.stringify(c))}
function gM(d){var dt=new Date(d.getFullYear(),d.getMonth(),d.getDate()),w=dt.getDay();if(!w)dt.setDate(dt.getDate()-6);else dt.setDate(dt.getDate()-w+1);return dt}
function gW(a,b){return Math.round((gM(a)-gM(b))/6048e5)}
function iB(dt,r,i){return gW(dt,r)%2===0?i:!i}
function iWD(y,m,d,c){var w=new Date(y,m,d).getDay();if(c.rest_mode==='double')return w>0&&w<6;if(c.rest_mode==='single')return c.single_rest_day==='saturday'?w!==5:w!==0;if(c.rest_mode==='alternate')return iB(new Date(y,m,d),new Date(c.ref_monday_ts),c.ref_is_big)?w!==0:w>0&&w<6;return true}
function cWD(y,m,c){var n=new Date(y,m+1,0).getDate(),t=0;for(var d=1;d<=n;d++)if(iWD(y,m,d,c))t++;return t}
function gDH(c){return Math.max(0,(toM(c.work_end)-toM(c.work_start)-toM(c.lunch_end)+toM(c.lunch_start))/60)}
function gDHT(c){var w=Math.max(0,(toM(c.work_end)-toM(c.work_start))-(toM(c.lunch_end)-toM(c.lunch_start)));return Math.floor(w/60)+'时'+(w%60?w%60+'分':'')}
function gDS(c){var dh=gDH(c);if(dh<=0)return 0;if(c.calc_mode==='legal')return c.salary/21.75;var n=new Date;if(!iWD(n.getFullYear(),n.getMonth(),n.getDate(),c))return 0;var wd=cWD(n.getFullYear(),n.getMonth(),c);return wd?c.salary/wd:0}
function gHR(c){var dh=gDH(c);if(dh<=0)return 0;if(c.calc_mode==='legal')return c.salary/174;var n=new Date;if(!iWD(n.getFullYear(),n.getMonth(),n.getDate(),c))return 0;var wd=cWD(n.getFullYear(),n.getMonth(),c);return wd?c.salary/(wd*dh):0}
function gEH(c){var n=new Date,s=n.getHours()*3600+n.getMinutes()*60+n.getSeconds(),ws=toM(c.work_start)*60,we=toM(c.work_end)*60,ls=toM(c.lunch_start)*60,le=toM(c.lunch_end)*60;if(s<=ws)return 0;if(s>=we)return(we-ws-(le-ls))/3600;var e=s-ws;if(s>le)e-=le-ls;else if(s>ls)e-=s-ls;return Math.max(0,e/3600)}
function gTE(c){var n=new Date;if(!iWD(n.getFullYear(),==='legal'?c.salary/21.75:0;var s=gSt(c);return s==='off'?gDS(c):gEH(c)*gHR(c)}
function gStn.getMonth(),n.getDate(),c))return c.calc_mode(c){var n=new Date;if(!iWD(n.getFullYear(),n.getMonth(),n.getDate(),c))return'rest';var s=n.getHours()*3600+n.getMinutes()*60+n.getSeconds(),ws=toM(c.work_start)*60,we=toM(c.work_end)*60,ls=toM(c.lunch_start)*60,le=toM(c.lunch_end)*60;if(s<ws)return'waiting';if(s>=we)return'off';if(s>=ls&&s<le)return'lunch';return'working'}
function render(){if(!cfg)return;var n=new Date,y=n.getFullYear(),m=n.getMonth(),d=n.getDate(),hh=n.getHours(),mi=n.getMinutes(),ss=n.getSeconds();$('cH').textContent=(hh<10?'0':'')+hh;$('cM').textContent=(mi<10?'0':'')+mi;$('cS').textContent=(ss<10?'0':'')+ss;$('dL').textContent=y+'年'+(m<9?'0':'')+(m+1)+'月'+(d<10?'0':'')+d+'日 '+WK[n.getDay()];var st=gSt(cfg),clr=st==='working'?'rgba(45,214,122,.1)':st==='waiting'?'rgba(91,141,239,.1)':st==='lunch'?'rgba(232,184,75,.1)':st==='rest'?'rgba(140,100,200,.1)':'rgba(255,255,255,.04)',fclr=st==='working'?'#2dd67a':st==='waiting'?'#5b8def':st==='lunch'?'#e8b84b':st==='rest'?'#a080d0':'#8a869a',stxt=st==='working'?'工作中':st==='waiting'?'等待上班':st==='lunch'?'午休中':st==='rest'?'今日休息':'已下班';$('bdg').style.background=clr;$('bdg').style.color=fclr;$('stx').textContent='● '+stxt;if(cfg.rest_mode==='alternate'){var big=iB(n,new Date(cfg.ref_monday_ts),cfg.ref_is_big);$('wkT').style.display='';$('wkT').textContent=big?'大周':'小周';$('wkT').style.background=big?'rgba(232,184,75,.1)':'rgba(91,141,239,.1)';$('wkT').style.color=big?'#e8b84b':'#5b8def'}else $('wkT').style.display='none';var ds=gDS(cfg),hr=gHR(cfg),te=gTE(cfg),iw=iWD(y,m,d,cfg);$('tE').textContent=te.toFixed(2);var wd=cWD(y,m,cfg),dh=gDH(cfg),daily=ds,past=0;for(var dd=1;dd<d;dd++)if(iWD(y,m,dd,cfg))past++;$('mE').textContent=(past*daily+te).toFixed(2);var pct=dh>0?Math.min(100,gEH(cfg)/dh*100):0;if(!iw)pct=st==='off'?100:0;$('pp').textContent=Math.round(pct)+'%';$('pfl').style.width=pct+'%';$('iH').textContent=gDHT(cfg);if(iw||cfg.calc_mode==='legal'){$('iDS').textContent='¥'+ds.toFixed(1);$('iR').textContent='¥'+hr.toFixed(1)}else{$('iDS').textContent='¥0';$('iR').textContent='¥0'}var ns=hh*3600+mi*60+ss;if(st==='off'||st==='rest'){$('iT').textContent=st==='off'?'已下班':'--'}else{var tgt=st==='waiting'?toM(cfg.work_start)*60:toM(cfg.work_end)*60,df=Math.max(0,tgt-ns);$('iT').textContent=(df<10?'0':'')+Math.floor(df/3600)+':'+((df%3600)/60<10?'0':'')+Math.floor((df%3600)/60)}var pd=cfg.pay_day,md=new Date(y,m+1,0).getDate();if(d===pd)$('iP').textContent='今天';else if(d<pd)$('iP').textContent=(pd-d)+'天';else $('iP').textContent=(md-d+pd)+'天';var rmEl=$('rm');if(st==='off'){rmEl.style.display='block';rmEl.innerHTML='<div>上班辛苦了，今日赚取</div><div class="ra">¥'+te.toFixed(2)+'</div>'}else if(st==='rest'){rmEl.style.display='block';rmEl.innerHTML=cfg.calc_mode==='legal'?'<div>放假快乐！今日赚取</div><div class="ra">¥'+te.toFixed(2)+'</div>':'<div>放假快乐！</div>'}else rmEl.style.display='none';$('fi').textContent='本月'+wd+'个工作日·已过'+past+'天·剩余'+Math.max(0,wd-past-(iw?1:0))+'天'}
function openS(){if(cfg){$('fS').value=cfg.salary;$('fWS').value=cfg.work_start;$('fWE').value=cfg.work_end;$('fLS').value=cfg.lunch_start;$('fLE').value=cfg.lunch_end;$('fPD').value=cfg.pay_day;sRM(cfg.rest_mode);sRD(cfg.single_rest_day);sAW(cfg.ref_is_big?'big':'small');sCM(cfg.calc_mode||'actual');tc=cfg.text_color||'#eae6de';ec=cfg.earn_color||'#e8b84b';apL(cfg)}$('ov').classList.add('on');$('sh').classList.add('on')}
function closeS(){$('ov').classList.remove('on');$('sh').classList.remove('on')}
function sRM(v){document.querySelectorAll('#rmG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'});$('sRW').className=v==='single'?'sr2 show':'sr2';$('aRW').className=v==='alternate'?'sr2 show':'sr2'}
function sRD(v){document.querySelectorAll('#rdG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'})}
function sAW(v){document.querySelectorAll('#awG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'})}
function sCM(v){document.querySelectorAll('#cmG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'});$('cmD').innerHTML=v==='legal'?'时薪=月薪÷174小时，日薪=月薪÷21.75天':'时薪=月薪÷当月工作日÷日工时'}
function toast(m){var t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(function(){t.classList.remove('show')},1600)}
$('bS').onclick=openS;$('bT').onclick=openS;$('bC').onclick=closeS;$('ov').onclick=closeS;
$('zI').onclick=function(){if(zl<300){zl+=10;aZ()}};$('zO').onclick=function(){if(zl>30){zl-=10;aZ()}};$('zR').onclick=function(){zl=100;aZ()};
$('fCO').oninput=pvL;$('fBO').oninput=pvL;
$('bpU').onclick=function(){$('bfi').click()};
$('bfi').onchange=function(e){var f=e.target.files[0];if(!f)return;var r=new FileReader();r.onload=function(ev){localStorage.setItem('dayW3bg',ev.target.result);lBg();toast('背景已更换')};r.readAsDataURL(f)};
$('bpRs').onclick=function(){localStorage.removeItem('dayW3bg');lBg();toast('已恢复默认')};
document.querySelectorAll('#rmG .op').forEach(function(b){b.onclick=function(){sRM(this.getAttribute('data-v'))}});
document.querySelectorAll('#rdG .op').forEach(function(b){b.onclick=function(){sRD(this.getAttribute('data-v'))}});
document.querySelectorAll('#awG .op').forEach(function(b){b.onclick=function(){sAW(this.getAttribute('data-v'))}});
document.querySelectorAll('#cmG .op').forEach(function(b){b.onclick=function(){sCM(this.getAttribute('data-v'))}});
$('bSv').onclick=function(){var salary=parseInt($('fS').value,10);if(!salary||salary<=0){alert('请输入有效月薪');return}var ws=$('fWS').value,we=$('fWE').value,ls=$('fLS').value,le=$('fLE').value;if(!ws||!we||!ls||!le){alert('请填写完整时间');return}if(toM(we)<=toM(ws)){alert('下班必须晚于上班');return}if(toM(le)<=toM(ls)){alert('午休结束必须晚于开始');return}if(!(toM(ws)<=toM(ls)&&toM(le)<=toM(we))){alert('午休需在上下班时间内');return}var pd=parseInt($('fPD').value,10);if(!pd||pd<1||pd>28){alert('发薪日请输入1-28');return}var rm=document.querySelector('#rmG .op.on'),rd=document.querySelector('#rdG .op.on'),aw=document.querySelector('#awG .op.on'),cm=document.querySelector('#cmG .op.on');cfg={salary:salary,work_start:ws,work_end:we,lunch_start:ls,lunch_end:le,rest_mode:rm?rm.getAttribute('data-v'):'double',single_rest_day:rd?rd.getAttribute('data-v'):'sunday',ref_monday_ts:gM(new Date).getTime(),ref_is_big:aw?aw.getAttribute('data-v')==='big':true,pay_day:pd,calc_mode:cm?cm.getAttribute('data-v'):'actual',text_color:tc,earn_color:ec,card_op:parseInt($('fCO').value),bord_op:parseInt($('fBO').value)};sS(cfg);apL(cfg);closeS();showMain();toast('设置已保存')};
function showMain(){$('emp').style.display='none';$('mc').style.display='block'}
var sz=localStorage.getItem('dayW3z');if(sz)zl=parseInt(sz,10);aZ();
mkP('tcR','tcI',{v:tc});mkP('ecR','ecI',{v:ec});
cfg=lCfg();
if(cfg){if(!cfg.ref_monday_ts)cfg.ref_monday_ts=gM(new Date).getTime();if(cfg.ref_is_big==null)cfg.ref_is_big=true;if(!cfg.calc_mode)cfg.calc_mode='actual';if(!cfg.text_color)cfg.text_color='#eae6de';if(!cfg.earn_color)cfg.earn_color='#e8b84b';if(cfg.card_op==null)cfg.card_op=85;if(cfg.bord_op==null)cfg.bord_op=6;apL(cfg);showMain();lBg()}
render();setInterval(render,500);
document.addEventListener('visibilitychange',function(){if(!document.hidden)render()});
window.addEventListener('focus',function(){setTimeout(render,50)});
})();
