function mkP(rid,iid,ref){
var r=$(rid),all=['#000000','#44546A','#4472C4','#ED7D31','#A5A5A5','#FFC000','#5B9BD5','#70AD47','#D6DCE4','#D9E2F3','#FCE4D6','#EDEDED','#FFF2CC','#DEEBF6','#E2EFDA','#ADB9CA','#B4C6E7','#F8CBAD','#DBDBDB','#FFE699','#BDD7EE','#C5E0B3','#8496B0','#8EAADB','#F4B183','#C9C9C9','#FFD966','#9CC3E5','#A8D08D','#5B758E','#5B9BD5','#C55A11','#FFC000','#2E75B6','#548235','#C00000','#FF0000','#FFFF00','#92D050','#00B050','#00B0F0','#0070C0','#002060','#7030A0'];
all.forEach(function(c){var d=document.createElement('div');d.className='cs2';d.style.background=c;d.setAttribute('data-c',c);d.onclick=function(){ref.v=c;$(iid).value=c;r.querySelectorAll('.cs2').forEach(function(x){x.classList.toggle('on',x.getAttribute('data-c')===c)});pvL()};r.appendChild(d)});
$(iid).oninput=function(){ref.v=this.value;r.querySelectorAll('.cs2').forEach(function(x){x.classList.remove('on')});pvL()};
}
function pvL(){$('mc').style.color=TC;document.documentElement.style.setProperty('--earn',EC);var co=+$('fCO').value||85,bo=+$('fBO').value||6;document.documentElement.style.setProperty('--cop',co/100);document.documentElement.style.setProperty('--bop',bo/100);$('fCOv').textContent=co+'%';$('fBOv').textContent=bo+'%'}
function apL(c){TC=c.text_color||'#eae6de';EC=c.earn_color||'#e8b84b';$('mc').style.color=TC;document.documentElement.style.setProperty('--earn',EC);var co=c.card_op!=null?c.card_op:85,bo=c.bord_op!=null?c.bord_op:6;document.documentElement.style.setProperty('--cop',co/100);document.documentElement.style.setProperty('--bop',bo/100);$('tcI').value=TC;$('ecI').value=EC;$('fCO').value=co;$('fBO').value=bo;$('fCOv').textContent=co+'%';$('fBOv').textContent=bo+'%';document.querySelectorAll('#tcR .cs2').forEach(function(x){x.classList.toggle('on',x.getAttribute('data-c')===TC)});document.querySelectorAll('#ecR .cs2').forEach(function(x){x.classList.toggle('on',x.getAttribute('data-c')===EC)})}
function lBg(){var b=localStorage.getItem('dayW3bg');if(b){$('bpI').src=b;$('bpI').style.display='block';$('bpP').style.display='none';$('mc').style.backgroundImage='url('+b+')';$('mc').classList.add('hb')}else{$('bpI').style.display='none';$('bpP').style.display='flex';$('mc').style.backgroundImage='none';$('mc').classList.remove('hb')}}
function aZ(){document.documentElement.style.setProperty('sc',ZL/100);$('zV').textContent=ZL+'%';localStorage.setItem('dayW3z',ZL)}
function toast(m){var t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(function(){t.classList.remove('show')},1600)}
function sRM(v){document.querySelectorAll('#rmG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'});$('sRW').className=v==='single'?'sr2 show':'sr2';$('aRW').className=v==='alternate'?'sr2 show':'sr2'}
function sRD(v){document.querySelectorAll('#rdG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'})}
function sAW(v){document.querySelectorAll('#awG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'})}
function sCM(v){document.querySelectorAll('#cmG .op').forEach(function(b){b.className=b.getAttribute('data-v')===v?'op on':'op'});$('cmD').innerHTML=v==='legal'?'时薪=月薪÷174小时':'时薪=月薪÷当月工作日÷日工时'}
function openS(){$('mc').style.display='block';if(G){$('fS').value=G.salary;$('fWS').value=G.work_start;$('fWE').value=G.work_end;$('fLS').value=G.lunch_start;$('fLE').value=G.lunch_end;$('fPD').value=G.pay_day;sRM(G.rest_mode);sRD(G.single_rest_day);sAW(G.ref_is_big?'big':'small');sCM(G.calc_mode||'actual');TC=G.text_color||'#eae6de';EC=G.earn_color||'#e8b84b';apL(G)}$('ov').classList.add('on');$('sh').classList.add('on')}
function closeS(){$('ov').classList.remove('on');$('sh').classList.remove('on');if(!G)$('mc').style.display='none'}
